import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  likecount: 0,
  karzinka: 0,
  caruselImg: [
    {
      image: "./img/carusel/7.jpg",
      caption: "Qulay Mebellar ",
    },
    {
      image: "./img/carusel/2.jpg",
      caption: "Qulay Mebellar",
    },
    {
      image: "./img/carusel/3.jpg",
      caption: "Qulay Mebellar",
    },
    {
      image: "./img/carusel/10.jpg",
      caption: "Qulay Mebellar",
    },
    {
      image: "./img/carusel/5.jpg",
      caption: "Qulay Mebellar",
    },
    {
      image: "./img/carusel/6.jpg",
      caption: "Qulay Mebellar",
    },
    {
      image: "./img/carusel/1.jpg",
      caption: "Qulay Mebellar",
    },
    {
      image: "./img/carusel/8.jpg",
      caption: "Qulay Mebellar",
    },
    {
      image: "./img/carusel/9.jpg",
      caption: "Qulay Mebellar",
    },
    {
      image: "./img/carusel/10.jpg",
      caption: "Qulay Mebellar",
    },
  ],
  katalog: [
    { id: 1, img: "./img/katalog/1.png", title: "Kuxni" },
    { id: 2, img: "./img/katalog/2.png", title: "Spalni" },
    { id: 3, img: "./img/katalog/3.png", title: "Detski" },
    { id: 4, img: "./img/katalog/4.png", title: "Shkaf" },
    { id: 5, img: "./img/katalog/5.png", title: "Stol-Stul" },
    { id: 6, img: "./img/katalog/6.png", title: "Mexmonxona" },
    { id: 7, img: "./img/katalog/7.png", title: "Devan" },
    { id: 8, img: "./img/katalog/8.png", title: "Kuxni" },
  ],
  dataDefault: [
    {
      id: 1,
      name: "ishxona uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/1.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 25,
      holati: true,
    },
    {
      id: 2,
      name: "Bolalar uchun",
      viloyat: "Toshkent",
      tuman: "Boka",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/2.png",
        "./img/katalog/1.png",
        "./img/katalog/3.png",
      ],
      sort: "Bolalar",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 3,
      name: "Yotoqxona uchun",
      viloyat: "Namangan",
      tuman: "Toroqorgon",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/3.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Devan",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 0,
      holati: true,
    },
    {
      id: 4,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Pop",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/4.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 5,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 6,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Toshkent",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 13000,
      skitka: 20,
      holati: false,
    },
    {
      id: 7,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 8,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Namangan",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 9,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 10,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 11,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 12,
      name: "Shkaf uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 13,
      name: "Shkaf uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 14,
      name: "ishxona uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/1.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 25,
      holati: true,
    },
    {
      id: 15,
      name: "Bolalar uchun",
      viloyat: "Toshkent",
      tuman: "Boka",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/2.png",
        "./img/katalog/1.png",
        "./img/katalog/3.png",
      ],
      sort: "Bolalar",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 16,
      name: "Yotoqxona uchun",
      viloyat: "Namangan",
      tuman: "Toroqorgon",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/3.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Devan",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 0,
      holati: true,
    },
    {
      id: 17,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Pop",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/4.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 18,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 19,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Toshkent",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 13000,
      skitka: 20,
      holati: false,
    },
    {
      id: 20,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 21,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Namangan",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 22,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 23,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 24,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 25,
      name: "Shkaf uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 26,
      name: "Shkaf uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 27,
      name: "ishxona uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/1.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 25,
      holati: true,
    },
    {
      id: 28,
      name: "Bolalar uchun",
      viloyat: "Toshkent",
      tuman: "Boka",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/2.png",
        "./img/katalog/1.png",
        "./img/katalog/3.png",
      ],
      sort: "Bolalar",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 29,
      name: "Yotoqxona uchun",
      viloyat: "Namangan",
      tuman: "Toroqorgon",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/3.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Devan",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 0,
      holati: true,
    },
    {
      id: 30,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Pop",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/4.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 31,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 32,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Toshkent",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 13000,
      skitka: 20,
      holati: false,
    },
    {
      id: 33,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 34,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Namangan",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 35,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 36,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 37,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 38,
      name: "Shkaf uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 39,
      name: "Shkaf uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 40,
      name: "ishxona uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/1.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 25,
      holati: true,
    },
    {
      id: 41,
      name: "Bolalar uchun",
      viloyat: "Toshkent",
      tuman: "Boka",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/2.png",
        "./img/katalog/1.png",
        "./img/katalog/3.png",
      ],
      sort: "Bolalar",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 42,
      name: "Yotoqxona uchun",
      viloyat: "Namangan",
      tuman: "Toroqorgon",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/3.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Devan",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 0,
      holati: true,
    },
    {
      id: 43,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Pop",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/4.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 44,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 45,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Toshkent",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 13000,
      skitka: 20,
      holati: false,
    },
    {
      id: 46,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 47,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Namangan",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 48,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 49,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 50,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 51,
      name: "Shkaf uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 52,
      name: "Shkaf uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 53,
      name: "ishxona uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/1.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 25,
      holati: true,
    },
    {
      id: 54,
      name: "Bolalar uchun",
      viloyat: "Toshkent",
      tuman: "Boka",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/2.png",
        "./img/katalog/1.png",
        "./img/katalog/3.png",
      ],
      sort: "Bolalar",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 55,
      name: "Yotoqxona uchun",
      viloyat: "Namangan",
      tuman: "Toroqorgon",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/3.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Devan",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 0,
      holati: true,
    },
    {
      id: 56,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Pop",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/4.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 57,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 58,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Toshkent",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 13000,
      skitka: 20,
      holati: false,
    },
    {
      id: 59,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 60,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Namangan",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 61,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 62,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 63,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 64,
      name: "Shkaf uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 65,
      name: "Shkaf uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 66,
      name: "ishxona uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/1.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 25,
      holati: true,
    },
    {
      id: 67,
      name: "Bolalar uchun",
      viloyat: "Toshkent",
      tuman: "Boka",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/2.png",
        "./img/katalog/1.png",
        "./img/katalog/3.png",
      ],
      sort: "Bolalar",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 68,
      name: "Yotoqxona uchun",
      viloyat: "Namangan",
      tuman: "Toroqorgon",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/3.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Devan",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 0,
      holati: true,
    },
    {
      id: 69,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Pop",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/4.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 70,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 71,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Toshkent",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 13000,
      skitka: 20,
      holati: false,
    },
    {
      id: 72,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 73,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Namangan",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 74,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 75,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 76,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 77,
      name: "Shkaf uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 78,
      name: "Shkaf uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 79,
      name: "ishxona uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/1.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 25,
      holati: true,
    },
    {
      id: 80,
      name: "Bolalar uchun",
      viloyat: "Toshkent",
      tuman: "Boka",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/2.png",
        "./img/katalog/1.png",
        "./img/katalog/3.png",
      ],
      sort: "Bolalar",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 81,
      name: "Yotoqxona uchun",
      viloyat: "Namangan",
      tuman: "Toroqorgon",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/3.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Devan",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 0,
      holati: true,
    },
    {
      id: 82,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Pop",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/4.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 83,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 84,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Toshkent",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 13000,
      skitka: 20,
      holati: false,
    },
    {
      id: 85,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 86,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Namangan",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 87,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 88,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 89,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 90,
      name: "Shkaf uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 91,
      name: "Shkaf uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 92,
      name: "ishxona uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/1.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 25,
      holati: true,
    },
    {
      id: 93,
      name: "Bolalar uchun",
      viloyat: "Toshkent",
      tuman: "Boka",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/2.png",
        "./img/katalog/1.png",
        "./img/katalog/3.png",
      ],
      sort: "Bolalar",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 94,
      name: "Yotoqxona uchun",
      viloyat: "Namangan",
      tuman: "Toroqorgon",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/3.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Devan",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 0,
      holati: true,
    },
    {
      id: 95,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Pop",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/4.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 96,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 97,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Toshkent",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 13000,
      skitka: 20,
      holati: false,
    },
    {
      id: 98,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 99,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Namangan",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 100,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 101,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 102,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 103,
      name: "Shkaf uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 104,
      name: "Shkaf uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 105,
      name: "ishxona uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/1.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 25,
      holati: true,
    },
    {
      id: 106,
      name: "Bolalar uchun",
      viloyat: "Toshkent",
      tuman: "Boka",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/2.png",
        "./img/katalog/1.png",
        "./img/katalog/3.png",
      ],
      sort: "Bolalar",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 107,
      name: "Yotoqxona uchun",
      viloyat: "Namangan",
      tuman: "Toroqorgon",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/3.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Devan",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 0,
      holati: true,
    },
    {
      id: 108,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Pop",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/4.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 109,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 110,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Toshkent",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 13000,
      skitka: 20,
      holati: false,
    },
    {
      id: 111,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 112,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Namangan",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 113,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 114,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 115,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 116,
      name: "Shkaf uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 117,
      name: "Shkaf uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 118,
      name: "ishxona uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/1.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 25,
      holati: true,
    },
    {
      id: 119,
      name: "Bolalar uchun",
      viloyat: "Toshkent",
      tuman: "Boka",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/2.png",
        "./img/katalog/1.png",
        "./img/katalog/3.png",
      ],
      sort: "Bolalar",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 120,
      name: "Yotoqxona uchun",
      viloyat: "Namangan",
      tuman: "Toroqorgon",
      brend:{name:'BBB',img:'./img/brend/images (1).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/3.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Devan",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 0,
      holati: true,
    },
    {
      id: 121,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Pop",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/4.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 10,
      holati: false,
    },
    {
      id: 122,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 123,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Toshkent",
      brend:{name:'AAA',img:'./img/brend/images (2).jfif'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 13000,
      skitka: 20,
      holati: false,
    },
    {
      id: 124,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Mexmonxona",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id:125,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Namangan",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 126,
      name: "kuxna uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 127,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 128,
      name: "kuxna uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'DDD',img:'./img/brend/images (1).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "kuxni",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 129,
      name: "Shkaf uchun",
      viloyat: "Namangan",
      tuman: "Mingbuloq",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
    {
      id: 130,
      name: "Shkaf uchun",
      viloyat: "Toshkent",
      tuman: "Mirzo Ulugbek",
      brend:{name:'CCC',img:'./img/brend/images (2).png'},
      buyurtma: false,
      img: [
        "./img/katalog/5.png",
        "./img/katalog/2.png",
        "./img/katalog/3.png",
      ],
      sort: "Shkaf",
      imgbtnCount: 0,
      colorCount: 0,
      color: ["green", "grey", "orange", "red"],
      like: false,
      count: 1,
      razmer: { buyi: "2-metr", eni: "1-metr", qalinligi: "1.5-sm" },
      narx: 123000,
      skitka: 50,
      holati: false,
    },
 
  ],
  data: [],
  qilinganIshalr: [
    {
      id: 1,
      class: " a",
      name: "Kuxni",
      img: "./img/ishlar/image 7.png",
      img2: "./img/ishlar/image 8.png",
      img3: "./img/ishlar/image 7.png",
    },
    {
      id: 2,
      class: " b",
      name: "Mexmonxona",
      img: "./img/ishlar/image 7 (1).png",
      img2: "./img/ishlar/image 9.png",
      img3: "./img/ishlar/image 7.png",
    },
    {
      id: 3,
      class: " c",
      name: "Kuxni AAA",
      img: "./img/ishlar/image 9.png",
      img2: "./img/ishlar/image 8.png",
      img3: "./img/ishlar/image 7.png",
    },
    {
      id: 4,
      class: " d",
      name: "Kuxni BBB",
      img: "./img/ishlar/image 8.png",
      img2: "./img/ishlar/image 8.png",
      img3: "./img/ishlar/image 7.png",
    },
  ],
  kategoryabtns: [
    "All",
    "Kuxni",
    "Mexmonxona",
    "Devan",
    "Shkaf",
    "Bolalar",
    "Romlar",
    "Activlar",
    "Skitkalar",
  ],
  qilinganishlarImgs: [
    {
      id: 1,
      categorya: "kuxni",
      img: [
        "./img/ishlar/image 7.png",
        "./img/ishlar/image 7.png",
        "./img/ishlar/image 7.png",
      ],
    },
    {
      id: 2,
      categorya: "Mexmonxona",
      img: [
        "./img/ishlar/image 7 (1).png",
        "./img/ishlar/image 7 (1).png",
        "./img/ishlar/image 7 (1).png",
      ],
    },
    {
      id: 3,
      categorya: "aaa",
      img: [
        "./img/ishlar/image 9.png",
        "./img/ishlar/image 9.png",
        "./img/ishlar/image 9.png",
      ],
    },
    {
      id: 4,
      categorya: "bbb",
      img: [
        "./img/ishlar/image 8.png",
        "./img/ishlar/image 8.png",
        "./img/ishlar/image 8.png",
      ],
    },
  ],
  brend: [
    { id: 1, img: "./img/brend/images (1).jfif", name: "AAA" },
    { id: 2, img: "./img/brend/images (2).jfif", name: "BBB" },
    { id: 3, img: "./img/brend/images (1).png", name: "DDD" },
    { id: 4, img: "./img/brend/images (2).png", name: "CCC" },
    { id: 5, img: "./img/brend/images (1).jfif", name: "DDD" },
    { id: 3, img: "./img/brend/images (1).png", name: "EEE" },
    { id: 4, img: "./img/brend/images (2).png", name: "FFF" },
    { id: 8, img: "./img/brend/images (1).jfif", name: "GGG" },
  ],
  brendfilter:'',
  viloyat:'',
  tuman:'',
};

export const HomeReducer = createSlice({
  name: "home",
  initialState,
  reducers: {
    imgbtnCount: (state, action) => {
      state.data = state.data.map((val) =>
        val.id === action.payload[0].id
          ? { ...action.payload[0], imgbtnCount: action.payload[1] }
          : val
      );
    },
    colorCounts: (state, action) => {
      state.data = state.data.map((val) =>
        val.id === action.payload[0].id
          ? { ...action.payload[0], colorCount: action.payload[1] }
          : val
      );
    },

    buyurtmafun: (state, action) => {
      if (action.payload.buyurtma === false) {
        state.data = state.data.map((val) =>
          val.id === action.payload.id
            ? { ...action.payload, buyurtma: true }
            : val
        );
      } else {
        state.data = state.data.map((val) =>
          val.id === action.payload.id
            ? { ...action.payload, buyurtma: false }
            : val
        );
      }
      let savathisob = state.data.filter((val) => val.buyurtma === true);
      state.karzinka = savathisob.length;
    },
    likefun: (state, action) => {
      if (action.payload.like === false) {
        state.data = state.data.map((val) =>
          val.id === action.payload.id ? { ...action.payload, like: true } : val
        );
      } else {
        state.data = state.data.map((val) =>
          val.id === action.payload.id
            ? { ...action.payload, like: false }
            : val
        );
      }
      let likehisob = state.data.filter((val) => val.like === true);
      state.likecount = likehisob.length;
    },
    savatCount: (state, action) => {
        state.data = state.data.map((val) =>
          val.id === action.payload.id ? { ...action.payload, count: action.payload.count +1 } : val
        );
    },
    savatCountdecr: (state, action) => {
        state.data = state.data.map((val) =>
          val.id === action.payload.id ? { ...action.payload, count: (action.payload.count >1? action.payload.count -1:1) } : val
        );
    },
    SearchFilter: (state, action) => {
        state.data = action.payload 
    },
    brencountfunc: (state, action) => {
        state.brendfilter = action.payload 
    },
    viloyatcountfunc: (state, action) => {
        state.viloyat = action.payload 
    },
    tumancountfunc: (state, action) => {
        state.tuman = action.payload 
    },
   
  },
});

// Action creators are generated for each case reducer function
export const {
  imgbtnCount,
  colorCounts,
  buyurtmafun,
  likefun,
  kategoryabtns,
  SearchFilter,
  savatCount,
  savatCountdecr,
  brencountfunc,
  tumancountfunc,
  viloyatcountfunc
} = HomeReducer.actions;

export default HomeReducer.reducer;
